### ISSUE TITLE
PoC for using Netlify

### ISSUE THREAD

**Issue by altinnadmin** [Altinn/altinn-infoportal#1]
If we're going to use GitHub-flow and markdown + Hugo for maintaining the content on altinn.no, it should be easy also for those without at technical background to edit and add new pages.

A possible solution is to use [Netlify CMS](https://www.netlifycms.org/) for providing a simple GUI on top.
Netlify already has [support for Hugo](https://docs.netlify.com/configure-builds/common-configurations/hugo/).

## Tasks

- [x] [Add Netlify](https://www.netlifycms.org/docs/hugo/#getting-started-with-netlify-cms) to the PoC so it can be tested locally
   - [x] Update README
- [x] Test some page types, for example news, etc.
- [x] Test [support for shortcodes](https://www.netlifycms.org/docs/hugo/#using-hugo-shortcodes-in-the-markdown-editor)
- [x] Test GitHub flow (pull requests and QA) using Netlify
- [x] Language support in Netlify
