### ISSUE TITLE
Search using Elastic Cloud

### ISSUE THREAD

**Issue by altinnadmin** [Altinn/altinn-infoportal#8]
## Description
We should update the infoportal poc to start using Elastic Cloud when searching. Currently search is missing completely in the poc.
A bonus is that this also can be used when testing https://github.com/Altinn/dig-portfolio/issues/6.

## Screenshot
![image](https://user-images.githubusercontent.com/6088624/150479997-9e6d6048-212d-4812-9021-43fc831b0f2c.png)

## Tasks

- [ ] Implement search page: https://infoportal.no/sok
- [ ] Connect to new search APIs in Elastic Cloud (client side using javascript if possible)
   - [ ] Stretch target: Add autocomplete (missing in altinn.no)
- [ ] Add search from [front-page](https://infoportal.no/), [help](https://infoportal.no/hjelp/), [starte og drive](https://infoportal.no/starte-og-drive/), footer and all other places where the search component is used.
